import { HashRouter, Routes, Route, NavLink, Link, useParams } from 'react-router-dom'
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip } from 'recharts'
import { VIDEOS, CATEGORIES, PATTERNS, COACHING, PERFECT_DEMO } from './data'
import './index.css'

function scoreColor(pct: number) {
  if (pct >= 0.75) return '#15803d'
  if (pct >= 0.55) return '#b45309'
  return '#dc2626'
}

function ScoreBadge({ score, max }: { score: number; max: number }) {
  const pct = score / max
  return (
    <span style={{ color: scoreColor(pct), fontWeight: 700 }}>
      {score}/{max}
    </span>
  )
}

function ProgressBar({ score, max }: { score: number; max: number }) {
  const pct = score / max
  return (
    <div style={{ height: 6, background: '#e5e7eb', borderRadius: 9999, overflow: 'hidden' }}>
      <div style={{ height: '100%', width: `${pct * 100}%`, background: scoreColor(pct), borderRadius: 9999 }} />
    </div>
  )
}

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', fontFamily: '-apple-system, Helvetica Neue, Arial, sans-serif', background: '#f9fafb', color: '#111827' }}>
      <div style={{ height: 3, background: '#FF3621' }} />
      <header style={{ background: '#0f1629', color: '#fff', position: 'sticky', top: 0, zIndex: 30, borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
        <div style={{ maxWidth: 900, margin: '0 auto', padding: '0 24px', height: 52, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}>
          <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 10, color: '#fff', textDecoration: 'none' }}>
            <div style={{ height: 28, width: 28, borderRadius: 4, background: '#FF3621', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <svg viewBox="0 0 20 20" style={{ height: 14, width: 14, fill: '#fff' }}><path d="M3 4h14v2H3zm0 5h10v2H3zm0 5h14v2H3z"/></svg>
            </div>
            <span style={{ fontWeight: 600, fontSize: 13, letterSpacing: '-0.01em' }}>ODI Demo Analyzer</span>
          </Link>
          <nav style={{ display: 'flex', gap: 4, fontSize: 12, fontWeight: 500 }}>
            {[['/', 'Scoreboard'], ['/patterns', 'Patterns'], ['/coaching', 'Coaching']].map(([to, label]) => (
              <NavLink key={to} to={to} end={to === '/'} style={({ isActive }) => ({ padding: '5px 10px', borderRadius: 4, color: isActive ? '#fff' : 'rgba(255,255,255,0.55)', background: isActive ? 'rgba(255,255,255,0.12)' : 'transparent', textDecoration: 'none' })}>
                {label}
              </NavLink>
            ))}
          </nav>
        </div>
      </header>
      <main style={{ flex: 1, maxWidth: 900, margin: '0 auto', width: '100%', padding: '32px 24px' }}>{children}</main>
      <footer style={{ borderTop: '1px solid #e5e7eb', background: '#fff' }}>
        <div style={{ maxWidth: 900, margin: '0 auto', padding: '12px 24px', fontSize: 11, color: '#9ca3af' }}>
          Fivetran ODI Demo Analyzer &nbsp;·&nbsp; Rubric v1.0 &nbsp;·&nbsp; June 2026 &nbsp;·&nbsp; Scores generated by AI analysis against the ODI messaging rubric
        </div>
      </footer>
    </div>
  )
}

function Scoreboard() {
  const sorted = [...VIDEOS].sort((a, b) => b.total - a.total)
  return (
    <div>
      <div style={{ marginBottom: 32 }}>
        <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#FF3621', marginBottom: 4 }}>Demo Review — June 2026</p>
        <h1 style={{ fontSize: 28, fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 8 }}>ODI Demo Scores</h1>
        <p style={{ fontSize: 14, color: '#6b7280', maxWidth: 500 }}>Three Fivetran demo videos scored against the ODI messaging rubric. Click any video for the full category breakdown.</p>
      </div>

      <div style={{ display: 'grid', gap: 12, marginBottom: 32 }}>
        {sorted.map((v, i) => (
          <Link key={v.id} to={`/video/${v.id}`} style={{ display: 'block', background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20, textDecoration: 'none', color: 'inherit', transition: 'border-color 0.15s' }}
            onMouseEnter={e => (e.currentTarget.style.borderColor = '#FF3621')}
            onMouseLeave={e => (e.currentTarget.style.borderColor = '#e5e7eb')}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
              <div style={{ fontSize: 28, fontWeight: 900, color: '#e5e7eb', width: 28, flexShrink: 0 }}>#{i + 1}</div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 2 }}>
                  <span style={{ fontWeight: 700, fontSize: 15 }}>{v.presenter}</span>
                  <span style={{ color: '#d1d5db', fontSize: 13 }}>·</span>
                  <span style={{ color: '#6b7280', fontSize: 13 }}>{v.title}</span>
                  <span style={{ color: '#d1d5db', fontSize: 13 }}>·</span>
                  <span style={{ color: '#9ca3af', fontSize: 12 }}>{v.duration}</span>
                </div>
                <p style={{ fontSize: 13, color: '#6b7280', marginBottom: 12, lineHeight: 1.5, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' as const }}>{v.verdict}</p>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <div style={{ flex: 1, height: 7, background: '#f3f4f6', borderRadius: 9999, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${v.total}%`, background: scoreColor(v.total / 100), borderRadius: 9999 }} />
                  </div>
                  <span style={{ fontSize: 22, fontWeight: 900, color: scoreColor(v.total / 100), flexShrink: 0 }}>{v.total}</span>
                  <span style={{ fontSize: 13, color: '#9ca3af', flexShrink: 0 }}>/100</span>
                </div>
              </div>
            </div>
          </Link>
        ))}
      </div>

      <div style={{ background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 10, padding: '16px 20px', marginBottom: 24 }}>
        <p style={{ fontWeight: 600, color: '#92400e', marginBottom: 4, fontSize: 13 }}>Pattern across all three</p>
        <p style={{ fontSize: 13, color: '#92400e', lineHeight: 1.55 }}>All three videos are single-layer ingest demos. Not one mentions dbt, open formats (Iceberg or Delta Lake), or the destination analytics layer. The ODI story is structurally absent from all 58 combined minutes of footage.</p>
      </div>

      <div style={{ background: '#0f1629', borderRadius: 10, padding: '20px 24px' }}>
        <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'rgba(255,255,255,0.4)', marginBottom: 12 }}>Rubric — 100 points total</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 8 }}>
          {CATEGORIES.map(c => (
            <div key={c.id} style={{ background: 'rgba(255,255,255,0.05)', borderRadius: 6, padding: '10px 12px' }}>
              <div style={{ fontSize: 11, color: 'rgba(255,255,255,0.4)', marginBottom: 2 }}>{c.name}</div>
              <div style={{ fontWeight: 800, fontSize: 17, color: '#fff' }}>{c.max} pts</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

function VideoDetail() {
  const { id } = useParams<{ id: string }>()
  const v = VIDEOS.find(x => x.id === id)
  if (!v) return <div style={{ textAlign: 'center', padding: '80px 0', color: '#9ca3af' }}>Video not found</div>

  const radarData = CATEGORIES.map((c, i) => ({
    subject: c.name.split(' ').slice(0, 2).join(' '),
    pct: Math.round((v.categories[i].score / c.max) * 100),
  }))

  return (
    <div>
      <Link to="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 13, color: '#6b7280', textDecoration: 'none', marginBottom: 20 }}>
        ← All videos
      </Link>

      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16, flexWrap: 'wrap', marginBottom: 16 }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <h1 style={{ fontSize: 24, fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 4 }}>{v.presenter}</h1>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: '#6b7280', flexWrap: 'wrap' }}>
            <span>{v.title}</span><span>·</span><span>{v.duration}</span><span>·</span>
            <a href={v.url} target="_blank" rel="noopener noreferrer" style={{ color: '#FF3621', textDecoration: 'none' }}>Watch on Loom ↗</a>
          </div>
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <div style={{ fontSize: 48, fontWeight: 900, lineHeight: 1, color: scoreColor(v.total / 100) }}>{v.total}</div>
          <div style={{ fontSize: 12, color: '#9ca3af' }}>out of 100</div>
        </div>
      </div>

      <div style={{ background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: 8, padding: '12px 16px', fontSize: 13, color: '#374151', fontStyle: 'italic', marginBottom: 24, lineHeight: 1.5 }}>
        "{v.verdict}"
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
        <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#9ca3af', marginBottom: 16 }}>Score breakdown</p>
          <div style={{ display: 'grid', gap: 10 }}>
            {CATEGORIES.map((c, i) => (
              <div key={c.id}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3, fontSize: 13 }}>
                  <span style={{ color: '#374151' }}>{c.name}</span>
                  <ScoreBadge score={v.categories[i].score} max={c.max} />
                </div>
                <ProgressBar score={v.categories[i].score} max={c.max} />
              </div>
            ))}
          </div>
        </div>
        <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#9ca3af', marginBottom: 8 }}>Radar</p>
          <ResponsiveContainer width="100%" height={240}>
            <RadarChart data={radarData} margin={{ top: 10, right: 20, bottom: 10, left: 20 }}>
              <PolarGrid stroke="#e5e7eb" />
              <PolarAngleAxis dataKey="subject" tick={{ fontSize: 9, fill: '#9ca3af' }} />
              <Radar dataKey="pct" stroke={scoreColor(v.total / 100)} fill={scoreColor(v.total / 100)} fillOpacity={0.15} strokeWidth={2} />
              <Tooltip formatter={(val) => [`${Number(val)}%`, "Score"]} />
            </RadarChart>
          </ResponsiveContainer>
          <p style={{ fontSize: 11, color: '#9ca3af', textAlign: 'center' }}>% of category max</p>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
        <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#15803d', marginBottom: 12 }}>What works</p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: 8 }}>
            {v.strengths.map((s, i) => (
              <li key={i} style={{ display: 'flex', gap: 8, fontSize: 13, color: '#374151', lineHeight: 1.45 }}>
                <span style={{ color: '#15803d', fontWeight: 700, flexShrink: 0 }}>+</span><span>{s}</span>
              </li>
            ))}
          </ul>
        </div>
        <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#dc2626', marginBottom: 12 }}>What to fix</p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: 8 }}>
            {v.gaps.map((g, i) => (
              <li key={i} style={{ display: 'flex', gap: 8, fontSize: 13, color: '#374151', lineHeight: 1.45 }}>
                <span style={{ color: '#dc2626', fontWeight: 700, flexShrink: 0 }}>−</span><span>{g}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: 20, marginBottom: 16 }}>
        <h2 style={{ fontWeight: 700, fontSize: 15, marginBottom: 16 }}>Category detail</h2>
        <div style={{ display: 'grid', gap: 0 }}>
          {CATEGORIES.map((c, i) => (
            <div key={c.id} style={{ borderBottom: i < CATEGORIES.length - 1 ? '1px solid #f3f4f6' : 'none', padding: '14px 0' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4, fontSize: 13 }}>
                <span style={{ fontWeight: 600, color: '#111827' }}>{c.name}</span>
                <ScoreBadge score={v.categories[i].score} max={c.max} />
              </div>
              <p style={{ fontSize: 13, color: '#6b7280', lineHeight: 1.55 }}>{v.categories[i].rationale}</p>
            </div>
          ))}
        </div>
      </div>

      <div style={{ background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: 8, padding: '10px 14px', fontSize: 12, color: '#6b7280' }}>
        <b>Audience:</b> {v.audience} &nbsp;·&nbsp; <b>ODI coverage:</b> {v.odi_coverage}
      </div>
    </div>
  )
}

function Patterns() {
  return (
    <div>
      <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#FF3621', marginBottom: 4 }}>Cross-video analysis</p>
      <h1 style={{ fontSize: 28, fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 8 }}>Patterns</h1>
      <p style={{ fontSize: 14, color: '#6b7280', marginBottom: 28 }}>What all three videos have in common — good and bad.</p>
      <div style={{ display: 'grid', gap: 10, marginBottom: 32 }}>
        {PATTERNS.map((p, i) => (
          <div key={i} style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: '14px 18px', display: 'flex', gap: 12 }}>
            <span style={{ color: '#FF3621', fontWeight: 900, fontSize: 16, lineHeight: 1, flexShrink: 0, marginTop: 2 }}>{i + 1}</span>
            <p style={{ fontSize: 13, color: '#374151', lineHeight: 1.55 }}>{p}</p>
          </div>
        ))}
      </div>
      <div style={{ background: '#0f1629', borderRadius: 10, padding: '20px 24px' }}>
        <h2 style={{ fontWeight: 700, color: '#fff', marginBottom: 12, fontSize: 16 }}>What a 100/100 demo looks like</h2>
        <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.65)', lineHeight: 1.65, whiteSpace: 'pre-line' }}>{PERFECT_DEMO}</p>
      </div>
    </div>
  )
}

function Coaching() {
  return (
    <div>
      <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#FF3621', marginBottom: 4 }}>For presenters</p>
      <h1 style={{ fontSize: 28, fontWeight: 800, letterSpacing: '-0.02em', marginBottom: 8 }}>Coaching Recommendations</h1>
      <p style={{ fontSize: 14, color: '#6b7280', marginBottom: 28 }}>Five specific, actionable recommendations that apply across all three videos.</p>
      <div style={{ display: 'grid', gap: 12 }}>
        {COACHING.map((c, i) => (
          <div key={i} style={{ background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: '16px 20px', display: 'flex', gap: 14 }}>
            <div style={{ height: 28, width: 28, borderRadius: '50%', background: '#FF3621', color: '#fff', fontWeight: 700, fontSize: 13, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>{i + 1}</div>
            <div>
              <h3 style={{ fontWeight: 700, marginBottom: 4, fontSize: 14 }}>{c.title}</h3>
              <p style={{ fontSize: 13, color: '#6b7280', lineHeight: 1.55 }}>{c.detail}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default function App() {
  return (
    <HashRouter>
      <Layout>
        <Routes>
          <Route index element={<Scoreboard />} />
          <Route path="/video/:id" element={<VideoDetail />} />
          <Route path="/patterns" element={<Patterns />} />
          <Route path="/coaching" element={<Coaching />} />
        </Routes>
      </Layout>
    </HashRouter>
  )
}
